# app.py
# Main Streamlit app: MCQ → Analysis → Live Scripture Result

import streamlit as st

from questions import questions
from logic import analyze_emotion
from gita_fallback import GITA_VERSES


st.set_page_config(
    page_title="Emotion & Scripture Insight System",
    layout="centered"
)

# -----------------------
# Session State
# -----------------------
if "page" not in st.session_state:
    st.session_state.page = 0

if "answers" not in st.session_state:
    st.session_state.answers = [None] * len(questions)

if "analysis_result" not in st.session_state:
    st.session_state.analysis_result = None

if "scripture" not in st.session_state:
    st.session_state.scripture = None


# -----------------------
# PAGE 0 – Welcome
# -----------------------
if st.session_state.page == 0:
    st.title("🧠 Emotion & Scripture Insight System")

    st.write(
        """
        This system analyzes your emotional patterns using a psychological MCQ test
        and retrieves **authentic scripture passages** from open sources
        (Bible & Bhagavad Gita).

        ❗ No advice is generated.
        ❗ Only original text is shown.
        """
    )

    if st.button("Start"):
        st.session_state.page = 1
        st.rerun()


# -----------------------
# PAGE 1 – Instructions
# -----------------------
elif st.session_state.page == 1:
    st.header("📋 Instructions")

    st.write(
        """
        • There are **20 questions**  
        • Answer honestly  
        • No right or wrong answers  
        • Each question reflects a psychological pattern  
        """
    )

    if st.button("Begin Test"):
        st.session_state.page = 2
        st.rerun()


# -----------------------
# QUESTION PAGES (5 per page)
# Pages: 2,3,4,5
# -----------------------
elif 2 <= st.session_state.page <= 5:
    start = (st.session_state.page - 2) * 5
    end = start + 5

    st.header(f"Questions {start + 1} – {end}")

    for i in range(start, end):
        q = questions[i]
        options = list(q["options"].keys())

        # restore selected option safely
        previous_value = st.session_state.answers[i]
        default_index = 0
        if previous_value:
            for idx, opt in enumerate(options):
                if q["options"][opt] == previous_value:
                    default_index = idx
                    break

        selected = st.radio(
            q["q"],
            options,
            index=default_index,
            key=f"q{i}"
        )

        st.session_state.answers[i] = q["options"][selected]

    col1, col2 = st.columns(2)

    with col1:
        if st.button("Previous") and st.session_state.page > 2:
            st.session_state.page -= 1
            st.rerun()

    with col2:
        if st.button("Next"):
            st.session_state.page += 1
            st.rerun()


# -----------------------
# PAGE 6 – Analysis
# -----------------------
elif st.session_state.page == 6:
    st.header("🔍 Psychological Analysis")

    result = analyze_emotion(st.session_state.answers)
    st.session_state.analysis_result = result

    st.write("**Dominant Emotional Pattern:**")
    st.success(result["dominant_emotion"].replace("_", " ").title())

    st.write("**Secondary Traits:**")
    st.write(", ".join([t.replace("_", " ").title() for t in result["secondary_traits"]]))

    st.write("**Mental Balance Index:**")
    st.progress(result["mental_balance_index"] / 100)

    if st.button("Fetch Scripture Insight"):
        st.session_state.page = 7
        st.rerun()


# -----------------------
# PAGE 7 – LIVE SCRIPTURE RESULT
# -----------------------
elif st.session_state.page == 7:
    st.header("📖 Authentic Scripture Insight")

    dominant = st.session_state.analysis_result["dominant_emotion"]

    scripture = GITA_VERSES.get(dominant)

    if scripture:
        st.subheader("Source")
        st.write(scripture["source"])

        st.subheader("Reference")
        st.write(scripture["reference"])

        st.subheader("Original Text")
        st.info(scripture["text"])
    else:
        st.warning("No scripture mapped for this emotional state.")

    st.caption(
        "This content is provided from an offline, pre-verified scripture dataset. "
        "No interpretation or advice is generated by the system."
    )

    if st.button("Restart Test"):
        for key in list(st.session_state.keys()):
            del st.session_state[key]
        st.rerun()
