s = set()
n = int(input("Enter your number: "))
s.add(n)
n = int(input("Enter your number: "))
s.add(int(n))
n = int(input("Enter your number: "))
s.add(n)
n = int(input("Enter your number: "))
s.add(n)
n = int(input("Enter your number: "))
s.add(n)
n = int(input("Enter your number: "))
s.add(n)
n = int(input("Enter your number: "))
s.add(n)
n = int(input("Enter your number: "))
s.add(n)
n = int(input("Enter your number: "))
s.add(n)
print(s)